CREATE TABLE PERFIS (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_PERFIS PRIMARY KEY(ID)
);

INSERT INTO PERFIS(DESCRICAO) VALUES('Administrador');

CREATE TABLE USUARIOS (
	ID INT NOT NULL AUTO_INCREMENT,
	ID_PERFIL INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	CPF BIGINT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	
	CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
	CONSTRAINT FK_PERFIS FOREIGN KEY(ID_PERFIL) REFERENCES PERFIS(ID)
);

INSERT INTO USUARIOS(ID_PERFIL, NOME, SOBRENOME, CPF, EMAIL, SENHA)
VALUES(1, 'Fábio', 'Faraco', 15201259766, 'f.faraco27@gmail.com', 'admin');
